version = 0.1

[default.global.parameters]
stack_name = "hub-hungara-api"
region = "sa-east-1"

[default.deploy.parameters]
s3_bucket = "hub-hungara-sam-artifacts-622703417827"
s3_prefix = "hub-hungara-api"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
